### ISSUE TITLE
error - NotSupportedError: multipart/form-data not supported

### ISSUE THREAD

**Issue by erradi** [codersteps/nextjs_app_dir_file_uploader#1]
@codersteps
Thanks Abdessamad for your appreciated example. However, when I try it I get '**error - NotSupportedError: multipart/form-data not supported**'.
![image](https://user-images.githubusercontent.com/6945016/231272567-53f06cc1-e174-4ea9-acd1-dd13c7c61f16.png)
I appreciate your guidance to fix this issue.
Thanks

**Comment by abdessamadelhamdany** [comment]
Hello @erradi 
Thank you for reporting this issue, unfortunately, I'm not able to reproduce it on my end
Could your try adding the following at the end of the `upload/route.ts` file?

```ts
export const config = {
  api: {
    bodyParser: false,
  },
};
```

<img width="1246" alt="image" src="https://user-images.githubusercontent.com/20196583/231274994-caa4dace-bffa-4ac5-9510-07d7874954f4.png">

Thanks,

**Comment by abdessamadelhamdany** [comment]
Sorry to hear that, I will try it with Windows when I can, If I find anything I'll share it with you
Good luck 🙏

**Comment by abdessamadelhamdany** [comment]
Hello @erradi 
I've tested it on Windows 10, it's working the same way as in mac os
Please make sure you're using the latest Next.js version, cause I believe the formData is a new feature.
Thanks.
